[tool.poetry]
name = "suumo-analysis"
version = "0.1.0"
description = ""
authors = ["imnoida <82698327+imnoida@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.11,<3.13"
pandas = "^2.1.1"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
matplotlib = "^3.8.0"
ruff = "^0.1.2"

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"

[tool.ruff]
select = ["ALL"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
